project/thscoreboard/thscoreboard/urls.py
import logging

from django.contrib import admin
from django.urls import include, re_path, path
from django.views.generic import base as base_views
from django.shortcuts import render
from replays.views import index
from thscoreboard import settings
from thscoreboard.deploy import views as deploy_views

urlpatterns = [
    path("users/", include("users.urls")),
    path("", index.index),
    path("replays/", include("replays.urls.replay_urls")),
    path("docs/", include("replays.urls.docs_urls")),
    path("admin/", admin.site.urls),
    path("deploy", deploy_views.deploy),
    path("sysadmin/reload", deploy_views.reload),
    path("staff", lambda req: render(req, "staff.html")),
    # When fetching non-HTML pages, the browser looks at /favicon.ico
    # to find an icon.
    path(
        "favicon.ico",
        base_views.RedirectView.as_view(
            url="/static/favicon.ico",
            permanent=True,
        ),
    ),
]

# Install django-rosetta if (and only if) it is listed as an installed app.
# This should not be the case in prod.
if "rosetta" in settings.INSTALLED_APPS:
    logging.info("Including django-rosetta at /rosetta")
    urlpatterns += [re_path(r"^rosetta/", include("rosetta.urls"))]

project/thscoreboard/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from users.middleware import check_ban
from users import other_views
from users.views import (
    accept_invite,
    batch_invite_csv,
    banned,
    delete_account,
    profile,
    rankings,
    register,
    claim,
    set_language,
    my_claims,
)

from thscoreboard import settings

app_name = "users"

urlpatterns = [
    path("register", register.register, name="register"),
    path(
        "registration_success",
        register.registration_success,
        name="registration_success",
    ),
    path("preregistered", register.preregistered, name="preregistered"),
    path("verify_email/<str:token>", register.verify_email, name="verify_email"),
    path(
        "accept_invite/<str:token>", accept_invite.accept_invite, name="accept_invite"
    ),
    path("profile", profile.profile, name="profile"),
    path("delete_account", delete_account.delete_account, name="delete_account"),
    path("batch_invite", batch_invite_csv.batch_invite, name="batch_invite"),
    path(
        "batch_invite_confirm",
        batch_invite_csv.batch_invite_confirm,
        name="batch_invite_confirm",
    ),
    path("banned", banned.banned_notification, name="banned"),
    path("ip_bans/", other_views.view_ip_bans),
    path("ip_bans/add", other_views.add_ip_ban),
    path("ip_bans/<int:ban_id>/delete", other_views.delete_ip_ban),
    path("staff_ban", banned.staff_ban, name="staff_ban"),
    path("login", auth_views.LoginView.as_view(), name="login"),
    path(
        "logout",
        check_ban.allow_access_by_banned_users(auth_views.LogoutView.as_view()),
        name="logout",
    ),
    path(
        "change_password",
        auth_views.PasswordChangeView.as_view(),
        name="change_password",
    ),
    path(
        "forgot_password",
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy("users:forgot_password_sent"),
            extra_email_context={"site_base": settings.SITE_BASE},
        ),
        name="forgot_password",
    ),
    path(
        "forgot_password/sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_sent.html"
        ),
        name="forgot_password_sent",
    ),
    path(
        "forgot_password/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("users:forgot_password_complete")
        ),
        name="forgot_password_confirm",
    ),
    path(
        "forgot_password/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="forgot_password_complete",
    ),
    path("claim", claim.claim),
    path("set_language", set_language.set_language),
    path("claim/<int:claim_replay_request_id>", claim.review),
    path("my_claims", my_claims.my_claims),
    path("rankings", rankings.rankings),
]

project/thscoreboard/replays/views/user.py
"""The public page for a user's information."""

from django.contrib import auth
from django.shortcuts import get_object_or_404, render
from django.views.decorators import http as http_decorators

from replays import models
from replays.replays_to_json import convert_replays_to_json_bytes
from replays.views.replay_table_helpers import stream_json_bytes_to_http_reponse


@http_decorators.require_safe
def user_page_json(request, username: str):
    user = get_object_or_404(auth.get_user_model(), username=username, is_active=True)
    user_replays = (
        models.Replay.objects.select_related("rank_view")
        .filter(user=user)
        .order_by("shot__game_id", "shot_id", "created")
    )
    replay_jsons = convert_replays_to_json_bytes(user_replays)
    return stream_json_bytes_to_http_reponse(replay_jsons)


@http_decorators.require_safe
def user_page(request, username: str):
    user = get_object_or_404(auth.get_user_model(), username=username, is_active=True)
    is_own_page = user == request.user

    return render(
        request,
        "replays/user_page.html",
        {"viewed_user": user, "is_own_page": is_own_page},
    )

project/thscoreboard/users/views.py
"""Defines views for user and account management."""

from typing import Optional
from django.http import HttpResponseRedirect

from django.contrib import auth
from django.db import transaction
from django.shortcuts import render, redirect
from django.views.decorators import http as http_decorators

from . import send_email
from . import forms
from . import models


RegisterForm = forms.RegisterFormWithPasscode
_USE_PASSCODE = True


@http_decorators.require_http_methods(["GET", "HEAD", "POST"])
def register(request):
    """Start trying to register an account.

    The account registration flow works as follows:

    1. The user visits /register and sees a registration form, asking for a
       username, password and email address.
    2. If the user's selected username and email are not used by actual users,
       we add them to the "unverified_users" table, then send them an email.
       unverified_users are NOT real users; they do not block other users from
       registering with the given username or email address, and there are no
       unique columns on unverified_users. This means that username is not a
       primary key of this table.
    3. We send an email to the email address in question with a link to an
       "email verification" page, containing the primary key for their
       unverified_users user.
    4. If the user clicks that page, they see a confirmation page because
       I don't want to confirm somebody's account with a GET.
    5. If they POST there, they get a real account.
    6. TODO: We set up a cleanup cron job to delete temporary users so that we
       are not indefinitely holding these rows.

    TODO: If a user tries to log in as an unverified user, we should resend
    the notification email, even though they cannot log in yet.
    """
    if request.method == 'POST':
        try:
            form = RegisterForm(request.POST)

            if form.is_valid():
                passcode = models.EarlyAccessPasscode.objects.get(passcode=form.cleaned_data['passcode'])
                unverified_user = _preregister(
                    username=form.cleaned_data['username'],
                    email=form.cleaned_data['email'],
                    password=form.cleaned_data['password'],
                    passcode=passcode)
                send_email.SendVerificationEmail(request, unverified_user)
                return HttpResponseRedirect('./preregistered')
            
        except models.EarlyAccessPasscode.DoesNotExist:
            form.add_error('passcode', 'Early access; must provide a valid passcode')
    else:
        form = RegisterForm()

    return render(
        request, 'users/register.html',
        {
            'form': form,
            'require_passcode': _USE_PASSCODE
        })


@transaction.atomic
def _preregister(username, password, email, passcode: Optional[str]):
    # Create an unverified user.
    unverified_user = models.UnverifiedUser.CreateUser(username=username, email=email, raw_password=password)
    if passcode is not None:
        tie = models.UserPasscodeTie(unverified_user=unverified_user, passcode=passcode)
        tie.save()
    return unverified_user


@transaction.atomic
def _register(username, password, email, passcode):
    u = auth.get_user_model().objects.create_user(
        username=username,
        password=password,
        email=email
    )
    tie = models.UserPasscodeTie(user=u, passcode=passcode)
    tie.save()


def preregistered(request):
    return render(request, 'users/preregistered.html')


@http_decorators.require_safe
def registration_success(request):
    return render(request, 'users/registration_success.html')


@http_decorators.require_http_methods(['GET', 'HEAD', 'POST'])
def verify_email(request, token: str):
    try:
        unverified_user = models.UnverifiedUser.objects.get(token=token)
    except models.UnverifiedUser.DoesNotExist:
        return render(request, 'users/verify_email.html', {
            'unverified_user': None
        })

    if request.method == 'POST':
        unverified_user.VerifyUser()
        return redirect('users:registration_success')
    
    return render(request, 'users/verify_email.html', {
        # TODO: It would be nice to tell the user if it's too late and they are doomed.
        'unverified_user': unverified_user,
    })

project/thscoreboard/users/views/accept_invite.py
"""Contains views for players accepting invites to the site."""

from django.http import Http404

from django.contrib import auth
from django.shortcuts import render, redirect
from django.views.decorators import http as http_decorators

from users import forms
from users import models


@http_decorators.require_http_methods(["GET", "HEAD", "POST"])
def accept_invite(request, token: str):
    try:
        invited_user = models.InvitedUser.objects.get(token=token)
    except models.InvitedUser.DoesNotExist:
        raise Http404("We could not find your invite.")

    if request.method == "POST":
        form = forms.AcceptInviteForm(request.POST)
        if form.is_valid():
            new_acct = invited_user.AcceptInvite(form.cleaned_data["password"])
            auth.login(request, new_acct)
            return redirect("users:registration_success")
    else:
        form = forms.AcceptInviteForm(
            initial={
                "username": invited_user.username,
                "email": invited_user.email,
            }
        )

    return render(
        request,
        "users/accept_invite.html",
        {
            "form": form,
            "invited_user": invited_user,
        },
    )

project/thscoreboard/users/views/banned.py
"""This module contains information related to banned users."""

from django.contrib.auth import decorators as auth_decorators
from django.db import transaction
from django.shortcuts import render, redirect
from django.views.decorators import http as http_decorators

from users import forms
from users import models
from users.middleware import check_ban


@auth_decorators.login_required
@http_decorators.require_safe
@check_ban.allow_access_by_banned_users
def banned_notification(request):
    """Inform the user why they are banned."""

    with transaction.atomic():
        if not request.user.CheckIfBanned():
            # The user is not banned, just send them to the homepage.
            return redirect("/")

        latest_ban = models.Ban.objects.filter(target=request.user).order_by(
            "-expiration"
        )[0]

    return render(
        request,
        "users/banned.html",
        {
            "reason": latest_ban.reason,
            "expiration": latest_ban.expiration,
        },
    )


@auth_decorators.login_required
@auth_decorators.permission_required("staff", raise_exception=True)
def staff_ban(request):
    """A page where staff can temporarily ban other users."""
    if request.method == "POST":
        form = forms.BanForm(request.POST)
        if form.is_valid():
            target = form.cleaned_data["target"]
            target.BanUser(
                author=request.user,
                reason=form.cleaned_data["reason"],
                duration=form.GetDuration(),
            )

            if form.cleaned_data["also_delete_replays"]:
                target.DeleteAllReplays()

            return render(
                request,
                "users/ban_success.html",
                {"target": target},
            )

        # If the form is not valid, fall through to the GET page, and render it that way.
    else:
        form = forms.BanForm()

    return render(request, "users/ban_form.html", {"form": form})

project/thscoreboard/users/views/batch_invite_csv.py
"""Views related to batch-inviting users via CSV."""

import logging

from django.shortcuts import redirect, render
from django.views.decorators import http as http_decorators
from django.contrib.auth import decorators as auth_decorators

from users import forms
from users import models
from users import parse_invite_csv
from users import send_email


@auth_decorators.login_required
@auth_decorators.permission_required("staff", raise_exception=True)
@http_decorators.require_http_methods(["GET", "HEAD"])
def batch_invite(request):
    return render(
        request,
        "users/batch_invite_upload.html",
        {"form": forms.UploadInviteFileForm()},
    )


@auth_decorators.login_required
@auth_decorators.permission_required("staff", raise_exception=True)
@http_decorators.require_http_methods(["GET", "HEAD", "POST"])
def batch_invite_confirm(request):
    if request.method == "POST":
        button_value = request.POST.get("submit-button", "")
        if not button_value:
            print("not button value")
            return redirect("users:batch_invite")

        elif button_value == "Upload":
            _ = forms.UploadInviteFileForm(request.POST, request.FILES)

            if "invite_file" in request.FILES:
                invite_file = request.FILES["invite_file"]
                file_contents = invite_file.read()
                str_contents = file_contents.decode("utf-8")
                parsed_csv = parse_invite_csv.Parse(str_contents)

                confirm_form = forms.UploadInviteFileConfirmationForm(
                    initial={
                        "invite_file_contents": str_contents,
                    }
                )

                return render(
                    request,
                    "users/batch_invite_confirm.html",
                    {
                        "form": confirm_form,
                        "invite_rows": parsed_csv,
                        "is_error": any([not True for r in parsed_csv]),
                    },
                )

        elif button_value == "Confirm":
            confirm_form = forms.UploadInviteFileConfirmationForm(
                request.POST, request.FILES
            )
            if confirm_form.is_valid():
                parsed_csv = parse_invite_csv.Parse(
                    confirm_form.cleaned_data["invite_file_contents"]
                )

                for r in parsed_csv:
                    if r.errors:
                        logging.info(
                            "Parsed CSV had errors; not uploading.",
                            parsed_csv.errors_str,
                        )
                        raise Exception(parsed_csv.errors_str)

                for r in parsed_csv:
                    CreateInvitedUserAndSendEmail(r, request.user)

                return render(
                    request,
                    "users/batch_invite_success.html",
                    {
                        "count": len(parsed_csv),
                    },
                )
            else:
                raise Exception("Not valid :/")

    return redirect("users:batch_invite")


def CreateInvitedUserAndSendEmail(row: parse_invite_csv.Parse, inviter: models.User):
    invited = models.InvitedUser.CreateInvite(row.username, row.email, inviter)
    send_email.SendInviteEmail(invited)

project/thscoreboard/users/views/delete_account.py
"""This view lets a user delete their own account."""

from django.shortcuts import render
from django.views.decorators import http as http_decorators
from django.contrib.auth import decorators as auth_decorators

from users import forms
from users.middleware import check_ban


@auth_decorators.login_required
@http_decorators.require_http_methods(["GET", "HEAD", "POST"])
@check_ban.allow_access_by_banned_users
def delete_account(request):
    if request.method == "POST":
        form = forms.DeleteAccountForm(request.user, request.POST)
        if form.is_valid():
            request.user.MarkForDeletion()
            request.user.save()
            return render(request, "users/delete_account_successful.html")
    else:
        form = forms.DeleteAccountForm(request.user)

    return render(request, "users/delete_account.html", {"form": form})

project/thscoreboard/users/templates/users/ban_form.html
{% extends "base.html" %}

{% block content %}
<h2>Add Ban</h2>
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <table class="form-table">
        <th style="width: 50%;"></th>
        <tr>
            <td>
                <label for="{{ form.target.id_for_label }}">{{form.target.label}}</label>
                {{ form.target.errors }}
            </td>
            <td>
                {{ form.target }}
            </td>
        </tr>
        <tr>
            <td>
                <label for="{{ form.reason.id_for_label }}">{{form.reason.label}}</label>
                {{ form.reason.errors }}
            </td>
            <td>
                {{ form.reason }}
            </td>
        </tr>
        <tr>
            <td>
                <label for="{{ form.days.id_for_label }}">{{form.days.label}}</label>
                {{ form.days.errors }}
            </td>
            <td>
                {{ form.days }}
            </td>
        </tr>
        <tr>
            <td>
                <label for="{{ form.hours.id_for_label }}">{{form.hours.label}}</label>
                {{ form.hours.errors }}
            </td>
            <td>
                {{ form.hours }}
            </td>
        </tr>
        <tr>
            <td>
                <label for="{{ form.also_delete_replays.id_for_label }}">{{form.also_delete_replays.label}}</label>
                {{ form.also_delete_replays.errors }}
            </td>
            <td>
                {{ form.also_delete_replays }}
            </td>
        </tr>
    </table>
    <input type="submit">
</form>
{% endblock %}

project/thscoreboard/users/templates/users/ban_success.html
{% extends "simple_centered.html" %}
{% load i18n %}

{% block centered-title %}<p>Ban recorded</p>{% endblock %}

{% block centered-content %}
<p>{% blocktranslate with target_username=target.username %}
    The user {{target_username}} has been temporarily banned.
{% endblocktranslate %}</p>
{% endblock %}

project/thscoreboard/users/templates/users/banned.html
{% extends "simple_centered.html" %}
{% load i18n %}

{% block centered-title %}<p>Suspended</p>{% endblock %}

{% block centered-content %}
{% url 'Users/logout' as logout_url %}
{% url 'users:delete_account' as delete_account_url %}
<p>{% blocktranslate %}Your account has been suspended.{% endblocktranslate %}</p>

<p>{{reason}}</p>

<p>
    {% blocktranslate %}
        Your ban will end at {{ expiration }}, at which point you can use Silent Selene again.
        You may also <a href="{{ logout_url }}">log out</a> and browse anonymously.
    {% endblocktranslate %}
</p>
<p>
    {% blocktranslate %}
        You may still <a href="{{delete_account_url}}">delete your account</a>, though this
        will not shorten the length of the suspension.
    {% endblocktranslate %}
</p>
{% endblock %}

project/thscoreboard/users/templates/users/batch_invite_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Invite many users by uploading a CSV file</h1>

<p>
    This page is for staff only. Invite many users by uploading a CSV file
    containing their usernames and email addresses.
</p>

<table>
    <tr>
        <th scope="col">Username</th>
        <th scope="col">Email</th>
        <th score="col">Errors</th>
        <th score="col">Warnings</th>
    </tr>
    {% for invite in invite_rows %}
        <tr>
            <td>{{invite.username}}</td>
            <td>{{invite.email}}</td>
            <td>{{invite.errors_str}}</td>
            <td>{{invite.warnings_str}}</td>
        </tr>
    {% endfor %}
</table>


<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}

    {{ form.invite_file_contents.as_hidden }}

    <input type="submit" name="submit-button" value="Confirm" {% if is_error %}disabled{% endif %}>
</form>

{% endblock %}

project/thscoreboard/users/templates/users/batch_invite_success.html
{% extends "simple_centered.html" %}

{% block centered-content %}
<p>Successfully sent {{count}} invites.</p>

<p><a href="/users/batch_invite">Return to the batch invite page</a></p>
{% endblock %}

project/thscoreboard/users/templates/users/batch_invite_upload.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Invite many users by uploading a CSV file</h1>

<p>
    This page is for staff only. Invite many users by uploading a CSV file
    containing their usernames and email addresses.
</p>

<form action="batch_invite_confirm" method="post" enctype="multipart/form-data" class="inline-form upload-form">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="field-wrapper">
        {{ form.invite_file.errors }}
        <label for="{{form.invite_file.id_for_label}}">{% translate "Upload invite file:" %}</label>
        <input
            type="file"
            name="{{form.invite_file.name}}"
            required
            id="{{form.invite_file.id_for_label}}"
            accept=".csv"
            >
    </div>

    <input type="submit" name="submit-button" value="Upload">
</form>
{% endblock %}

project/thscoreboard/users/templates/users/delete_account.html
{% extends "simple_centered.html" %}
{% load i18n %}

{% block centered-title %}<p>Delete your account</p>{% endblock %}

{% block centered-content %}

<p>
    {% blocktranslate %}
    Are you sure you want to delete your account? This action cannot be undone,
    and will delete all of your replays.
    {% endblocktranslate %}
</p>

<p>
    {% blocktranslate %}
    If you're completely sure, confirm your password below.
    {% endblocktranslate %}
</p>

<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}

    <table class="form-table">
        <th style="width: 100%;"></th>
        <tr>
        <td>
            <label for="{{ form.password.id_for_label }}">{% translate 'Password' %}</label>
            {{ form.password.errors }}
        </td>
        <td>
            {{ form.password }}
        </td>
        </tr>
    </table>
    <input type="submit" value="Delete it!">
</form>

{% endblock %}

project/thscoreboard/users/templates/users/delete_account_successful.html
{% extends "simple_centered.html" %}
{% load i18n %}\

{% block centered-content %}

{% blocktranslate %}
<p>
    Your account has been deleted. Records and backups of your account may persist for some time after deletion.
</p>

<p>
    Thank you for using Silent Selene.
</p>
{% endblocktranslate %}

{% endblock %}

project/thscoreboard/users/templates/users/ip_bans.html
{% extends "base.html" %}

{% block content %}
<h2>IP Bans</h2>
<table class="replay-table">
<thead><tr>
    <th>IP</th>
    <th>Comment</th>
    <th>Author</th>
    <th>Delete</th>
</tr></thead>
<tbody>
{% for ip_ban in ip_bans %}
<tr>
    <td>{{ ip_ban.ip }}</td>
    <td>{{ ip_ban.comment }}</td>
    <td>{{ ip_ban.author }}</td>
    <td><a href={{ request.path }}{{ ip_ban.id }}/delete>Delete</a></td>
</tr>
{% endfor %}
</tbody>
</table>

<h2>Add IP Ban</h2>
<form method="post" action="{{ request.path }}add">
    {% csrf_token %}
    {{ add_ip_ban_form.non_field_errors }}
    <table class="form-table">
        <th style="width: 50%;"></th>
        <tr>
        <td>
            <label for="{{ add_ip_ban_form.ip.id_for_label }}">IP Address</label>
            {{ add_ip_ban_form.ip.errors }}
        </td>
        <td>
            {{ add_ip_ban_form.ip }}
        </td>
        </tr>
        <tr>
        <td>
            <label for="{{ add_ip_ban_form.comment.id_for_label }}">Comment</label>
            {{ add_ip_ban_form.comment.errors }}
        </td>
        <td>
            {{ add_ip_ban_form.comment }}
        </td>
        </tr>
    </table>
    <input type="submit" value="Add">
</form>
{% endblock %}

project/thscoreboard/users/templates/users/profile.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2>{% translate "My Profile" %}</h2>

<form method="post" class="form-flex">
    {% csrf_token %}

    <table class="form-table">
    <tbody>
        <th style="width: 50%;"></th>
        <tr>
        <td>
            <label for="{{form.username.id_for_label}}">{{form.username.label}}</label>
        </td>
        <td>
            {{ form.username }}
        </td>
        </tr>
        <tr>
        <td>
            <label for="{{form.password.id_for_label}}">{{form.password.label}}</label>
        </td>
        <td>
            {{ form.password }}
        </td>
        </tr>
        <tr>
        <td>
            <label for="{{form.email.id_for_label}}">{{form.email.label}}</label>
        </td>
        <td>
            {{ form.email }}
        </td>
        </tr>
    </tbody>
    </table>
</form>

<p><a href="{% url 'users:logout' %}">{% translate "Log out" %}</a></p>
<p><a href="{% url 'users:change_password' %}">{% translate "Change Password" %}</a></p>
<p><a href="{% url 'users:delete_account' %}">{% translate "Permanently delete my account" %}</a></p>

{% endblock %}

project/thscoreboard/users/templates/users/rankings.html
{% extends "base.html" %}

{% block content %}
<h1>Player Rankings</h1>

<form method="get">
    {% csrf_token %}
    {% for field_name, choice_field in form.all_choice_fields %}
        <div class="button-container">
            {% for choice_value, choice_label in choice_field.choices %}
                <button
                {% if choice_value == selection %}
                    class="button pressed"
                {% else %}
                    class="button"
                {% endif %}
                    type="submit"
                    name="{{ field_name }}"
                    value="{{ choice_value }}"
                >
                    {{ choice_label }}
                </button>
            {% endfor %}
        </div>
    {% endfor %}
</form>

<table class="replay-table">
    <thead>
        <tr>
            <th></th>
            <th>Player</th>
            <th>🥇</th>
            <th>🥈</th>
            <th>🥉</th>
        </tr>
    </thead>
    {% for row in rankings %}
        <tr>
            <td>{{ row.player_rank }}</td>
            <td>
                {% if row.username %}
                    {{ row.username }}
                {% else %}
                    <a href="/replays/user/{{ row.user }}">{{ row.user }}</a>
                {% endif %}
            </td>
            <td>{{ row.first_place_count }}</td>
            <td>{{ row.second_place_count }}</td>
            <td>{{ row.third_place_count }}</td>
        </tr>
    {% endfor %}
</table>

{% endblock %}

project/thscoreboard/users/templates/users/register.html
{% extends "simple_centered.html" %}

{% block centered-title %}<p>Register</p>{% endblock %}

{% block centered-content %}
<form method="post">
    {% csrf_token %} 
    {{ form.non_field_errors }}

    <table class="form-table">
        <th style="width: 100%;"></th>
        <tr>
        <td>
            <label for="{{ form.username.id_for_label }}">Username</label>
            {{ form.username.errors }}
        </td>
        <td>
            {{ form.username }}
        </td>
        </tr>
        <tr>
        <td>
            <label for="{{ form.email.id_for_label }}">Email Address</label>
            {{ form.email.errors }}
        </td>
        <td>
            {{ form.email }}
        </td>
        </tr>
        <tr>
            <td>
                {{ form.password.errors }}
                <label for="{{ form.password.id_for_label }}">Password</label>
            </td>
            <td>
                {{ form.password }}
            </td>
        </tr>
        {% if require_passcode %}
        <tr>
        <td>
            {{ form.passcode.errors }}
            <label for="{{ form.passcode.id_for_label }}">Early access passcode</label>
        </td>
        <td>
            {{ form.passcode }}
        </td>
        </tr>
        {% endif %}           
    </table>
    <br>
    <div>
        {{ form.accept_terms.errors }}
        {{ form.accept_terms }}
        <label for="{{ form.accept_terms.id_for_label }}">I accept the <a href="/docs/terms">terms of service</a></label>
    </div>

    <div>
    {{ form.accept_privacy.errors }}
    {{ form.accept_privacy }}
    <label for="{{ form.accept_privacy.id_for_label }}">I accept the <a href="/docs/privacy">privacy policy</a></label>
    </div>
    <br>

    <input type="submit" value="Register">
</form>
{% endblock %}

project/thscoreboard/users/templates/users/registration_success.html
{% extends "simple_centered.html" %}

{% block centered-content %}
<p>Thank you for joining Silent Selene and registering an account.</p>

<p><a href="/">Return to the home page</a></p>
{% endblock %}

project/thscoreboard/users/templates/users/verify_email.html
{% extends "simple_centered.html" %}

{% block centered-content %}
<p>
    Are you sure you want to register your account (with username {{unverified_user.username}})?
</p>
<p>
    <form method="POST">
        {% csrf_token %}

        <input type="submit" name="register" value="Register" />
    </form>
</p>
{% endblock %}